name: a_and_w
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  get_it: ^9.2.0
  go_router: ^17.1.0
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.8
  flutter_secure_storage: ^10.0.0
  meta: ^1.17.0
  dartz: ^0.10.1
  firebase_auth: ^6.1.4
  logger: ^2.6.2
  google_sign_in: ^6.2.2
  json_annotation: ^4.9.0
  cloud_firestore: ^6.1.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  bloc_test: ^10.0.0
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
