name: a_and_w
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  get_it: ^9.2.0
  go_router: ^17.1.0
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
